### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by memoryskull** [jnidzwetzki/bboxdb#166]
Hello @jnidzwetzki 
I want to create my portfolio and, therefore, I am contributing with open source repositories.
I can present you with a logo that represents your project without any commitment.

Thanks for your time.
Cheers!

**Comment by jnidzwetzki** [comment]
Hello @memoryskull,

Thanks for your offer and sorry for the long delay in answering your question. Your offer is very interesting for me. I am a terrible designer and also not entirely happy with the current logo. 

It is possible that you show me some of your past works? What license do your works have? 

Best Regards, and have a nice weekend.
   Jan
