### ISSUE TITLE
Is it available for any type of analysis? Can i load the data set?

### ISSUE THREAD

**Issue by Zaryab-Arif** [jnidzwetzki/bboxdb#86]
Hi,
Actually i want to perform some testing on this graph database. Is its data set is freely available?

**Comment by jnidzwetzki** [comment]
Hello,

You can use the CLI of BBoxDB to import datasets. You will find some documentation about this process here:

* https://jnidzwetzki.github.io/bboxdb/tools/cli.html (Section: Data Import)
* https://jnidzwetzki.github.io/bboxdb/tools/dataset.html (for converting OpenStreetMap data into GeoJSON)

Unfortunately, BBoxDB is not a graph database; it is a Key-Bounding-Box-Value Store (A Key-Value Store for multi-dimensional data). This software does not support graphs.

At the moment BBoxDB is listed in the wrong category on http://nosql-database.org/. I already created a PR to move BBoxDB into the 'Key Value / Tuple Store' category.

Best Regards
   Jan
